version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend

hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
